# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyderabad'), ('Bang', 'Bangalore'), ('Chen', 'Chennai'), ('Mum', 'Mumbai')], max_length=20)),
            ],
        ),
    ]
