# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
