# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=100)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('MySQL', 'MySQL'), ('Oracle', 'Oracle'), ('MSBI', 'MSBI'), ('REST API', 'REST API')], max_length=400)),
                ('faculty', multiselectfield.db.fields.MultiSelectField(choices=[('Nani', 'Nani'), ('Sai', 'Sai'), ('Raju', 'Raju'), ('Satya', 'Satya'), ('Rajesh', 'Rajesh')], max_length=500)),
                ('brance', multiselectfield.db.fields.MultiSelectField(choices=[('Branch-1', 'Branch-1'), ('Branch-2', 'Branch-2'), ('Branch-3', 'Branch-3')], max_length=500)),
            ],
        ),
    ]
